services:
  - type: web
    name: clouad
    runtime: node
    repo: https://github.com/ISSOLAHmelissa/esgi_render.git # nouveau repo
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString 
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start


# Exported from Render on 2024-12-19T08:28:06Z
databases:
- name: cloud-db
  databaseName: cloud_db_t99h
  plan: free
  region: frankfurt
  #ipAllowList:
  #- source: 0.0.0.0/0
    #description: everywhere
 # postgresMajorVersion: "16"
